package com.traceworthy.app

import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Document builders for the identity-theft pack. Self-contained — its own tiny
 * helpers so it doesn't couple to DocumentGenerator's private internals.
 *
 * TraceWorthy does not file anything. IdentityTheft.gov generates the official FTC
 * Identity Theft Report; these documents are the narrative, the account list, and
 * the letters the user sends alongside it.
 */
internal object IdentityTheftDocs {

    private val human = SimpleDateFormat("MMMM d, yyyy", Locale.US)

    private fun v(value: String, placeholder: String) = value.ifBlank { "[$placeholder]" }

    private fun footer() = Block.Body(
        "Generated by TraceWorthy on ${human.format(Date())}. Not legal advice — " +
            "TraceWorthy is an independent tool, not a law firm.",
    )

    fun build(type: DocumentType, case: Case, myInfo: MyInfo): List<Block> = when (type) {
        DocumentType.ItEvidencePacket -> evidencePacket(case, myInfo)
        DocumentType.ItEvidenceSummary -> evidenceSummary(case, myInfo)
        DocumentType.ItFtcCompanion -> ftcCompanion(case, myInfo)
        DocumentType.ItBureauLetters -> bureauLetters(case, myInfo)
        DocumentType.ItPoliceReport -> policeReport(case, myInfo)
        DocumentType.ItDisputeLetters -> disputeLetters(case, myInfo)
        else -> emptyList()
    }

    private val PACKET_CONTENTS = listOf(
        DocumentType.ItEvidenceSummary,
        DocumentType.ItFtcCompanion,
        DocumentType.ItBureauLetters,
        DocumentType.ItPoliceReport,
        DocumentType.ItDisputeLetters,
    )

    // -- shared pieces ---------------------------------------------------

    private fun complainant(myInfo: MyInfo): List<Block> = listOf(
        Block.Bullet("Name: ${v(myInfo.fullName, "YOUR FULL NAME")}"),
        Block.Bullet("Contact: ${v(myInfo.phone, "YOUR PHONE")} · ${v(myInfo.email, "YOUR EMAIL")}"),
        Block.Bullet("Location: ${v(myInfo.addressCity, "CITY")}, ${v(myInfo.state, "ST")}"),
    )

    private fun fraudTable(case: Case): List<Block> {
        if (case.fraudItems.isEmpty()) {
            return listOf(Block.Body("No fraudulent accounts have been added yet. Open \"Fraudulent " +
                "accounts\" and add each account, charge, or misuse you've found."))
        }
        return listOf(
            Block.Table(
                listOf("Kind", "Institution", "Ref", "Amount", "Discovered", "Status"),
                case.fraudItems.map {
                    listOf(it.kind.label, it.institution.ifBlank { "—" }, it.accountRef.ifBlank { "—" },
                        it.amount.ifBlank { "—" }, it.discoveredDate.ifBlank { "—" }, it.status.label)
                },
            ),
        )
    }

    private fun timeline(case: Case): List<Block> {
        val dated = case.fraudItems.filter { it.discoveredDate.isNotBlank() }
            .sortedBy { it.discoveredDate }
        if (dated.isEmpty()) return emptyList()
        val blocks = mutableListOf<Block>(Block.Heading("Discovery Timeline"))
        dated.forEach {
            blocks.add(Block.Bullet("${it.discoveredDate} — ${it.kind.label} at ${it.institution.ifBlank { "unknown" }}" +
                (if (it.amount.isNotBlank()) " (${it.amount})" else "")))
        }
        return blocks
    }

    // -- documents -----------------------------------------------------

    private fun evidenceSummary(case: Case, myInfo: MyInfo): List<Block> {
        val total = case.fraudItems.size
        val disputed = case.fraudItems.count { it.status == FraudStatus.Disputed || it.status == FraudStatus.Resolved }
        val blocks = mutableListOf<Block>(
            Block.Title("Identity Theft — Evidence Summary"),
            Block.Body("Prepared by ${v(myInfo.fullName, "YOUR FULL NAME")} · ${v(myInfo.phone, "YOUR PHONE")}"),
            Block.Body("Generated: ${human.format(Date())}"),
            Block.Gap(6f),
        )
        if (case.td("discovery").isNotBlank()) {
            blocks.add(Block.Body("How it started: ${case.td("discovery")}"))
        }
        blocks.add(Block.Heading("Complainant"))
        blocks.addAll(complainant(myInfo))
        blocks.add(Block.Heading("Reference Numbers"))
        blocks.add(Block.Bullet("FTC Identity Theft Report #: ${v(case.filing("ftc"), "FTC REPORT #")}"))
        blocks.add(Block.Bullet("Police case #: ${v(case.filing("police"), "POLICE CASE #")}"))
        blocks.add(Block.Bullet("Credit protection: ${
            when (case.td("creditProtection")) {
                "freeze" -> "credit frozen at all three bureaus"
                "alert" -> "one-year fraud alert placed"
                else -> "[not yet placed]"
            }
        }"))
        blocks.add(Block.Heading("Fraudulent Accounts And Charges ($total)"))
        blocks.addAll(fraudTable(case))
        if (total > 0) blocks.add(Block.Body("$disputed of $total have been formally disputed."))
        blocks.addAll(timeline(case))
        blocks.add(Block.Gap(8f))
        blocks.add(Block.Body("This summary accompanies the FTC Identity Theft Report and the dispute " +
            "correspondence. Supporting documents (statements, letters, the police report) are attached separately."))
        blocks.add(footer())
        return blocks
    }

    private fun ftcCompanion(case: Case, myInfo: MyInfo): List<Block> {
        val blocks = mutableListOf<Block>(
            Block.Title("FTC Identity Theft Report — Companion"),
            Block.Body("The official report is created at IdentityTheft.gov — answer its questions and " +
                "download the report and your personalized recovery plan. Use the narrative below in the " +
                "report's description box, and keep this page with the report."),
            Block.Gap(6f),
            Block.Heading("Narrative (Paste Into The Report)"),
            Block.Body("I am a victim of identity theft. ${case.td("discovery").ifBlank { "I do not know how my information was obtained." }} " +
                "Someone has used my personal information without my authorization to open accounts and/or " +
                "make charges in my name. I did not authorize, use, benefit from, or receive any goods, " +
                "services, or money from the accounts and transactions listed below. I am requesting that " +
                "this report be used to block and remove the fraudulent information under the Fair Credit " +
                "Reporting Act.", editable = true),
            Block.Heading("Fraudulent Accounts And Charges"),
        )
        blocks.addAll(fraudTable(case))
        blocks.add(Block.Heading("FTC Recovery Checklist"))
        listOf(
            "Place a free one-year fraud alert with one credit bureau (it notifies the other two), or " +
                "freeze your credit at all three to block new accounts.",
            "Get your free credit reports (annualcreditreport.com) and note every account and inquiry you don't recognize.",
            "Report to the FTC at IdentityTheft.gov and download the Identity Theft Report.",
            "File a report with your local police; bring the FTC report, a government ID, and proof of address.",
            "Close or freeze each fraudulent account — call the fraud department, then follow up in writing.",
            "Dispute the fraudulent items with each creditor and each credit bureau, attaching the FTC report.",
            "If your SSN was misused: contact the SSA (1-800-772-1213) and the IRS (Form 14039) as needed.",
            "Keep a log of every call and letter — who, when, what was said, and any reference number.",
        ).forEachIndexed { i, s -> blocks.add(Block.Bullet("${i + 1}. $s")) }
        blocks.add(Block.Gap(6f))
        blocks.add(footer())
        return blocks
    }

    private fun bureauLetters(case: Case, myInfo: MyInfo): List<Block> {
        val bureaus = listOf(
            Triple("Equifax", "Equifax Information Services LLC", "P.O. Box 105069, Atlanta, GA 30348-5069  ·  equifax.com/personal  ·  1-888-836-6351"),
            Triple("Experian", "Experian", "P.O. Box 9554, Allen, TX 75013  ·  experian.com/fraud  ·  1-888-397-3742"),
            Triple("TransUnion", "TransUnion LLC", "P.O. Box 2000, Chester, PA 19016  ·  transunion.com/fraud  ·  1-800-680-7289"),
        )
        val freeze = case.td("creditProtection") == "freeze"
        val ask = if (freeze) "place a security freeze on" else "place an initial one-year fraud alert on"
        val blocks = mutableListOf<Block>(
            Block.Title("Credit Bureau Letters"),
            Block.Body("Send one letter to each bureau by certified mail, or use the website / phone number " +
                "in each address block. A fraud alert is free, lasts one year, and one bureau notifies the " +
                "other two — a security freeze must be placed (and lifted) at each bureau separately but " +
                "blocks new credit entirely."),
        )
        bureaus.forEach { (short, legal, addr) ->
            blocks.add(Block.PageBreak)
            blocks.add(Block.Heading("To $short"))
            blocks.add(Block.Body(legal))
            blocks.add(Block.Body(addr))
            blocks.add(Block.Gap(6f))
            blocks.add(Block.Body("Date: ${human.format(Date())}"))
            blocks.add(Block.Body("Re: Identity theft — request to $ask my credit file"))
            blocks.add(Block.Gap(4f))
            blocks.add(Block.Body("To whom it may concern,"))
            blocks.add(Block.Body("I am a victim of identity theft. I am requesting that you $ask my credit " +
                "file. I have reported this to the Federal Trade Commission" +
                (if (case.filing("ftc").isNotBlank()) " (Identity Theft Report #${case.filing("ftc")})" else "") +
                (if (case.filing("police").isNotBlank()) " and to my local police (case #${case.filing("police")})" else "") +
                ". Copies are enclosed.", editable = true))
            blocks.add(Block.Body("My information:"))
            blocks.addAll(complainant(myInfo))
            blocks.add(Block.Body("I have enclosed a copy of a government-issued photo ID and proof of my " +
                "current address. Please send written confirmation once the request is processed, and a " +
                "free copy of my credit report so I can identify any fraudulent accounts."))
            blocks.add(Block.Body("Sincerely,"))
            blocks.add(Block.Body(v(myInfo.fullName, "YOUR FULL NAME")))
        }
        blocks.add(Block.Gap(6f))
        blocks.add(footer())
        return blocks
    }

    private fun policeReport(case: Case, myInfo: MyInfo): List<Block> {
        val blocks = mutableListOf<Block>(
            Block.Title("Identity Theft — Police Report Cover Note"),
            Block.Body("Bring this, your FTC Identity Theft Report, a government photo ID, and proof of " +
                "address to your local police department. Many departments will take an identity-theft " +
                "report on the strength of the FTC report."),
            Block.Gap(6f),
            Block.Heading("Complainant"),
        )
        blocks.addAll(complainant(myInfo))
        blocks.add(Block.Bullet("Date: ${human.format(Date())}"))
        blocks.add(Block.Heading("What Happened"))
        blocks.add(Block.Body("I am a victim of identity theft. ${case.td("discovery").ifBlank { "I do not know how my information was obtained." }} " +
            "My personal information has been used without my authorization to open accounts and/or make " +
            "charges in my name, listed below. I did not authorize or benefit from any of them.", editable = true))
        blocks.add(Block.Heading("Fraudulent Accounts And Charges"))
        blocks.addAll(fraudTable(case))
        blocks.addAll(timeline(case))
        blocks.add(Block.Heading("Cross-References"))
        blocks.add(Block.Bullet("FTC Identity Theft Report #: ${v(case.filing("ftc"), "FTC REPORT #")}"))
        blocks.add(Block.Heading("Request"))
        blocks.add(Block.Body("I am requesting that an identity-theft report be filed and a copy provided " +
            "to me, so I can send it to the creditors and credit bureaus involved. I understand a report " +
            "on file does not obligate the department to investigate."))
        blocks.add(Block.Gap(8f))
        blocks.add(footer())
        return blocks
    }

    private fun disputeLetters(case: Case, myInfo: MyInfo): List<Block> {
        val blocks = mutableListOf<Block>(
            Block.Title("Creditor Dispute Letters"),
            Block.Body("One letter per fraudulent account. Send each to the company's fraud / billing " +
                "department by certified mail, with a copy of your FTC Identity Theft Report, a government " +
                "ID, and proof of address enclosed. Under the Fair Credit Reporting Act (§ 605B) a company " +
                "must block information that resulted from identity theft once you provide the report."),
        )
        if (case.fraudItems.isEmpty()) {
            blocks.add(Block.Body("No fraudulent accounts have been added yet."))
            blocks.add(footer())
            return blocks
        }
        case.fraudItems.forEach { item ->
            blocks.add(Block.PageBreak)
            blocks.add(Block.Heading("To ${item.institution.ifBlank { "[CREDITOR / BANK NAME]" }}"))
            blocks.add(Block.Body("Fraud / Billing Department"))
            blocks.add(Block.Body("[Address — see your statement or the company's website]"))
            blocks.add(Block.Gap(6f))
            blocks.add(Block.Body("Date: ${human.format(Date())}"))
            blocks.add(Block.Body("Re: Identity theft — ${item.kind.label}" +
                (if (item.accountRef.isNotBlank()) ", account ending ${item.accountRef}" else "") +
                (if (item.amount.isNotBlank()) ", amount ${item.amount}" else "")))
            blocks.add(Block.Gap(4f))
            blocks.add(Block.Body("To whom it may concern,"))
            blocks.add(Block.Body("The account and/or charges referenced above are the result of identity " +
                "theft. I did not open this account, authorize it, use it, or receive any benefit from it. " +
                "I am requesting that you: (1) close the account and confirm I have no liability; " +
                "(2) stop reporting the account and any related debt to the credit bureaus and cease " +
                "collection activity; and (3) block the information under FCRA § 605B and notify any debt " +
                "collector to whom the account was referred.", editable = true))
            if (item.note.isNotBlank()) blocks.add(Block.Body("Details: ${item.note}"))
            blocks.add(Block.Body("Enclosed: my FTC Identity Theft Report" +
                (if (case.filing("ftc").isNotBlank()) " (#${case.filing("ftc")})" else "") +
                (if (case.filing("police").isNotBlank()) ", my police report (case #${case.filing("police")})" else "") +
                ", a government photo ID, and proof of my address."))
            blocks.add(Block.Body("My information:"))
            blocks.addAll(complainant(myInfo))
            blocks.add(Block.Body("Please respond in writing within 30 days. Sincerely,"))
            blocks.add(Block.Body(v(myInfo.fullName, "YOUR FULL NAME")))
        }
        blocks.add(Block.Gap(6f))
        blocks.add(footer())
        return blocks
    }

    private fun evidencePacket(case: Case, myInfo: MyInfo): List<Block> {
        val blocks = mutableListOf<Block>(
            Block.Title("Identity Theft Evidence Packet"),
            Block.Body("Prepared by ${v(myInfo.fullName, "YOUR FULL NAME")} · ${v(myInfo.phone, "YOUR PHONE")}"),
            Block.Body("Generated: ${human.format(Date())}"),
            Block.Gap(6f),
            Block.Body("This packet documents an identity-theft case: ${case.fraudItems.size} fraudulent " +
                "account(s)/charge(s). Keep it together with your FTC Identity Theft Report and every letter " +
                "you send and receive."),
        )
        blocks.add(Block.Heading("Contents"))
        PACKET_CONTENTS.forEachIndexed { i, t -> blocks.add(Block.Bullet("${i + 1}.  ${t.displayName}")) }
        blocks.add(Block.Heading("How To Use This Packet"))
        listOf(
            "Report to the FTC at IdentityTheft.gov and save the report number.",
            "Place a fraud alert or freeze using the credit-bureau letters.",
            "File a police report with the police report cover note + the FTC report.",
            "Send a dispute letter to each creditor with the FTC report attached; mark each account Disputed.",
            "Follow up in writing with anyone who doesn't respond within 30 days.",
        ).forEachIndexed { i, s -> blocks.add(Block.Bullet("${i + 1}. $s")) }
        PACKET_CONTENTS.forEach { t ->
            blocks.add(Block.PageBreak)
            blocks.addAll(build(t, case, myInfo))
        }
        return blocks
    }
}
